image: gitlab-registry.mpcdf.mpg.de/mpcdf/module-image

variables:
  GIT_SUBMODULE_STRATEGY: normal
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"


workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

tests:
  stage: test
  script:
    - module load git gcc/9 anaconda/3/2020.02
    - export CXX=g++
    - export CC=gcc
    - pip install -v .[tests]
    - pip install --upgrade numpy scipy
    - export PATH=$PATH:/root/.local/bin
    - pytest -v tests/

pages-test:
  stage: test
  script:
    - module load gcc/9 anaconda/3/2021.11 git
    - export CXX=g++
    - export CC=gcc
    - pip install .[docs]
    - export PATH=$PATH:/root/.local/bin
    - sphinx-build -W -b html doc/ doc-test/
  artifacts:
    paths:
      - doc-test
  rules:
    - if: '$CI_COMMIT_BRANCH != "main"'

pages:
  stage: deploy
  script:
    - module load gcc/9 anaconda/3/2021.11 git
    - export CXX=g++
    - export CC=gcc
    - pip install .[docs]
    - export PATH=$PATH:/root/.local/bin
    - sphinx-build -b html doc/ public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

